[project]
name = "py-gmail"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "google-api-python-client>=2.156.0",
    "google-auth-oauthlib>=1.2.1",
    "prompt-toolkit>=3.0.48",
    "rich>=13.9.4",
]
