version: '3'

tasks:
  default:
    deps:
      - run_windows
  
  run_windows:
    cmds:
      - powershell ./.venv/Scripts/activate; python -m pygmail.main

  clean:
    aliases:
      - c
    cmds:
      - rm token.pickle