version: '3'

tasks:
  default:
    deps: [run-windows]

  run-windows:
    cmds:
      - powershell ./.venv/Scripts/activate; python -m pygmail.main

  run-unix:
    cmds:
      - ./.venv/Scripts/activate & python -m pygmail.main

  clean:
    aliases:
      - c
    cmds:
      - rm token.pickle
